theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: releases/download/1.0/tinyTerm.exe
  tgz_url: releases/download/1.0/tinyTerm64.exe
  description: simple, small and scriptable terminal emulator
