theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/yongchaofan/tinyTerm/releases/download/1.2/tinyTerm-1.2.zip
  description: simple, small and scriptable terminal emulator
