theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/yongchaofan/tinyTerm/releases/download/R1.1/tinyTerm-1.1.zip
  description: simple, small and scriptable terminal emulator
